### ISSUE TITLE
Translator plugin not working in OJS 3.0

### ISSUE THREAD

**Issue by Abdel5** [pkp/translator#10]
Hi,

in my case translation plugin is not working in OJS 3.0. After installing it and enabling I have "Translate" link (.../management/settings/website?uid=57dad65587c86#translate) but it forwards me to Website->Apperance tab.

**Comment by asmecher** [comment]
Hi @Abdel5 -- how did you install it? I suspect it's not registered with the system.

**Comment by Abdel5** [comment]
Thanks for fast respond @asmecher.

I have tried to follow the readme file, in particular I:
- downloaded the file using "clone or download"
- changed permissions to local/ directory to 775 and owner to www-data,
- unpacked the file to plugins/generic directory
- executed $ php tools/upgrade.php upgrade
- enabled the plugin by going to:
  Management > Website Settings > Plugins > Generic Plugins
  ...and selecting the Enable checkbox beside "Translator Plugin"

As it was not working I executed upgrade.php one more time but still nothing. I have also cleared caches.

**Comment by asmecher** [comment]
@Abdel5, you can check if the plugin is registered properly by running in your database:

```
select * from versions where product_class_name='TranslatorPlugin';
```

**Comment by Abdel5** [comment]
@asmecher result of given SQL query is:

```
major   minor   revision    build   date_installed  current     product_type    product     product_class_name  lazy_load   sitewide
 2  0   0   0   2016-09-15 18:41:15     1   plugins.generic     translator  TranslatorPlugin    1   1
```

Also as long as I try to click "Translate" button from the site administration panel (and not journal administration panel) I get: 

> No journal in context!

**Comment by asmecher** [comment]
@Abdel5, OK, it sounds like the plugin has been installed and registered with the system. When you click "Translate", it's supposed to reload the settings tab set, and then there should be a new tab on the far right labeled "Translate". Is that not appearing?

**Comment by Abdel5** [comment]
@asmecher: When I click "Translate" I am being redirected to "Apperance" tab. The last tab on far right is "Announcements".

**Comment by Abdel5** [comment]
I have reinstalled OJS and tried to install "Translate" on clear installation but still the same problem with plug-in occurs.

**Comment by asmecher** [comment]
@Abdel5, would you be able to send me both a .tar.gz of your installation and a database dump? I haven't been able to replicate that behavior here, and those two would help me determine if it's some quirk of your PHP environment or something else.

**Comment by Abdel5** [comment]
@asmecher : Files and sql dump: http://files.mage.pl/czasopisma.sql http://files.mage.pl/czasopisma.tar.gz

I have changed the DB password on production after generating those files.

**Comment by Ingvar33** [comment]
@asmecher : I have the same problem. When I click "Translate" I am being redirected to "Apperance" tab. The last tab on far right is "Announcements". 
Use  OJS 3.0.

**Comment by asmecher** [comment]
@Abdel5 and @Ingvar33, I still haven't been able to replicate this locally. The above database dump appears to be gone; could one of the two of you send me a database dump? (If you're going to post it publicly, please make sure nothing important is in there.)

**Comment by Voytec749** [comment]
Hi! 

We've the same problem with OJS translator... We just make clean install of OJS 3.0.1 and unfortunately translator still not working. Here is our database dump (I've changed file extension from sql to txt): [ojs3.txt](https://github.com/pkp/translator/files/615883/ojs3.txt)

Thanks in advance for support.
Regards

**Comment by asmecher** [comment]
@Voytec749, when I log in using that database dump and go to Settings > Website, I see a tab on the far right labeled "Translate". Do you see that?

**Comment by Voytec749** [comment]
@asmecher, unfortunately, I don't see this tab... :(

![ojs](https://cloud.githubusercontent.com/assets/24221806/20784640/f0b88838-b79b-11e6-8976-6c4c7cf1f783.png)

**Comment by asmecher** [comment]
@Voytec749, what do you get for the following SQL query?

    select * from versions where product='translator';

**Comment by Voytec749** [comment]
@asmecher, here is a result: <table id="table_results" class="data ajax"><thead><tr>
<th class="draggable" data-column="major">major
</th><th class="draggable" data-column="minor">minor
</th><th class="draggable" data-column="revision">revision
</th><th class="draggable" data-column="build">build
</th><th class="draggable" data-column="date_installed">date_installed
</th><th class="draggable" data-column="current">current
</th><th class="draggable" data-column="product_type">product_type
</th><th class="draggable" data-column="product">product
</th><th class="draggable" data-column="product_class_name">product_class_name
</th><th class="draggable" data-column="lazy_load">lazy_load
</th><th class="draggable" data-column="sitewide">sitewide
</th></tr></thead><tbody>
<tr class="odd"><td data-decimals="0" data-type="int" class="right data grid_edit click2 not_null    nowrap ">2</td>
<td data-decimals="0" data-type="int" class="right data grid_edit click2 not_null    nowrap ">0</td>
<td data-decimals="0" data-type="int" class="right data grid_edit click2 not_null    nowrap ">0</td>
<td data-decimals="0" data-type="int" class="right data grid_edit click2 not_null    nowrap ">0</td>
<td data-decimals="0" data-type="datetime" class="data grid_edit click2 not_null   datetimefield nowrap ">2016-11-28 09:01:51</td>
<td data-decimals="0" data-type="int" class="right data grid_edit click2 not_null    nowrap ">1</td>
<td data-decimals="0" data-type="string" class="data grid_edit click2     ">plugins.generic</td>
<td data-decimals="0" data-type="string" class="data grid_edit click2     condition ">translator</td>
<td data-decimals="0" data-type="string" class="data grid_edit click2     ">TranslatorPlugin</td>
<td data-decimals="0" data-type="int" class="right data grid_edit click2 not_null    nowrap ">1</td>
<td data-decimals="0" data-type="int" class="right data grid_edit click2 not_null    nowrap ">1</td>
</tr>
</tbody>
</table>`

**Comment by asmecher** [comment]
@Voytec749, the Static Pages plugin uses a similar approach to inject a new tab to that interface. Could you try enabling that plugin to see if it suffers the same problem?

**Comment by asmecher** [comment]
Also, @Voytec749, is it possible that your file permissions in `cache/*.php` are set such that OJS can't update files there? (You might also consider removing all `.php` files from the `cache/` subdirectory, just to be sure old cache files aren't causing trouble.)

**Comment by Voytec749** [comment]
@asmecher, thank for your help!

The Static Pages plugin works fine - new tab is visible.

Unfortunately, Translator still doesn't work. We removed all `.php` files from `cache/` and they have been created again, so I think that permissions are set correctly (look at the screenshot). Additionaly, we launched the install script again - without any effect... :(

![cache](https://cloud.githubusercontent.com/assets/24221806/20877719/d7b7f3d2-baca-11e6-95a2-a4c2bf9e4f90.png)

**Comment by asmecher** [comment]
@Voytec749, thanks for the details -- hmm, this is getting hard to debug remotely and I can't duplicate that behavior over here. If I were debugging this, I would start using `error_log` statements to track down where the plugin is/isn't interacting with the system as expected.

In case you're not familiar with the plugin hook stuff, here's the basic picture:

- The plugin should be getting loaded fairly early in request handling, as it's a `generic` plugin.
- When the plugin is loaded, if the system thinks it's necessary, the plugin's `register` function will get called. (This should be happening because the plugin is enabled.)
- When the `register` function is called, the plugin should register against the `Templates::Management::Settings::website` hook. This is what it uses to inject the new tab.
- When that hook is encountered in building the page, the plugin's `callbackShowWebsiteSettingsTabs` function is called, which should inject the additional tab's markup.

**Comment by Voytec749** [comment]
@asmecher, lots of thanks for your involvement!

Is it possible that you help us remotely? Could you? We've prepared a clone of VM for you, so U can debug OJS on it. I've sent an email with credentials for you.

We've next question - how to easily copy `email_templates_default_data` db table to another language (`pl_PL`)? Can we simply duplicate records in `email_templates_default_data` table and change locale to `pl_PL`? (It seems that it works!) But this doesn't work through ojs admin panel (doesn't appear in PL locale after manually adding content like as another translation - eg. user roles). 

I don't understand difference between `email_templates / email_templates_data` and `email_templates_default / email_templates_default_data`

BTW - we've translated a lot of OJS from English to Polish manually by editing `*.xml` files, so we can share it :)

**Comment by asmecher** [comment]
I figured out the problem on @Voytec749's server -- the plugin was installed in `plugins/generic/translator-master` but the plugin's version descriptor (`version.xml`) specifies `<application>translator</application>`. The plugin code expects these two to be the same.

I ran...

    mv plugins/generic/translator-master plugins/generic/translator

...and the plugin started working.

I presume `translator-master` came from working with a download from Github. When we package up plugins into a `.tar.gz` or clone into a git checkout from command line, the branch name doesn't get included. One option would be to make the software not care about the directory name, but I'm not sure that's feasible, as the current assumption is made in order to improve performance (not e.g. having to load all plugins or parse their descriptors in order to determine which are enabled).

@Abdel5 and @Ingvar33, could you confirm whether this resolves the issue for you?

Note that we'll soon be adding plugins to the Plugin Gallery, including this one, making discovery/installation of plugins much easier. I'll also make a note to package up the translator plugin into a `.tar.gz` release.

**Comment by asmecher** [comment]
@Voytec749, regarding [your question about email templates](https://github.com/pkp/translator/issues/10#issuecomment-265092504) -- could you post this [in the forum](http://forum.pkp.sfu.ca/)? That'll help to keep things organized.

**Comment by Voytec749** [comment]
@asmecher, thank you very much! It works! :) We changed directory name on production server and translator plugin started working.

Regarding email templates, I found some information about it in the forum and i must check it out.
