### ISSUE TITLE
Cannot save translations with extended locale names (e.g. sr_RS@latin)

### ISSUE THREAD

**Issue by asmecher** [pkp/translator#28]
See https://forum.pkp.sfu.ca/t/ojs-3-1-translator-plugin-not-working/35156 for details.

**Comment by asmecher** [comment]
Either of the above patches (both are equivalent) needs to be applied in the OJS `lib/pkp` subdirectory to resolve the issue.

**Comment by knjigor** [comment]
@asmecher  
Thank you.
