### ISSUE TITLE
[OMP 3.1.1-3] blank page

### ISSUE THREAD

**Issue by gurumelo** [pkp/translator#35]
Hello.
We installed plugin translator

```
cd plugins/generic
git clone https://github.com/pkp/translator
cd ../../ && php tools/upgrade.php upgrade
[x] Translator
```

The result is, image
![t](https://screenshotscdn.firefoxusercontent.com/images/38fa93cc-978d-4873-bf47-17b8050f1543.png)

error.log

```
[Fri Jul 06 13:43:14.274488 2018] [cgi:error] [pid 31189] [client XX.XX.XX.43:58439] AH01215: PHP Fatal error:  Call to undefined method TranslatorPlugin::getTemplateResource() in /web/plugins/generic/translator/controllers/grid/LocaleGridHandler.inc.php on line 99, referer: https://XXXXXXXX/index.php/eual/management/settings/website?uid=5b3f55699e43e
```

Thanks

**Comment by asmecher** [comment]
@gurumelo, you're installing the current `master` branch, which isn't compatible with OMP 3.1.1-3. You need to either use the `ojs-stable-3_1_1` branch, or download the appropriate `.tar.gz` file from the Releases area.
