### ISSUE TITLE
OJS 3.1.1.2

### ISSUE THREAD

**Issue by redukr** [pkp/translator#38]
Hello! after installing and enabling plugin i've got balnk screen in "translate" section

Current version: 3.1.1.2 (July 15, 2018 - 02:13 PM)

I've  got 500 error

[17/Jul/2018:22:54:07 +0200] "GET /index.php/uars/$$$call$$$/plugins/generic/translator/controllers/grid/locale-grid/index?_=1531860709500 HTTP/1.1" 500 429 "https://uars.info/index.php/uars/management/settings/website$

[Tue Jul 17 22:54:07.994113 2018] [:error] [pid 8459] [client 192.168.1.105:53567] PHP Fatal error:  Call to undefined method TranslatorPlugin::getTemplateResource()  in /web/sites/uars/plugins/generic/translator/controllers/grid/LocaleGridHandler.inc.php on line 99, referer: https://uars.info/index.php/uars/management/settings/website

As i understand it calles to file named "locales.tpl"
But that file present at my site

I have attached google chrome error
[uars.info-1531861615516.log](https://github.com/pkp/translator/files/2203414/uars.info-1531861615516.log)

My server info: Setting Name | Setting Value
-- | --
OS platform | Linux
PHP version | 5.6.30-7+0~20170302103642.28+jessie~1.gbpe18d04
Apache version | Apache/2.4.10 (Debian)
Database driver | mysql
Database server version | 10.1.26-MariaDB-0+deb9u1

![1](https://user-images.githubusercontent.com/8823785/42844799-c9fde7ba-8a1c-11e8-971c-c0a0d14b6411.png)

**Comment by asmecher** [comment]
You've probably installed the current master branch, which isn't compatible with your installed version of OJS. Go to the "Releases" area to find the right download, or better yet, use the Plugin Gallery from inside OJS.
