### ISSUE TITLE
double-check language in en_US locale: plugins.generic.translator.file.confirmCreate

### ISSUE THREAD

**Issue by mtub** [pkp/translator#8]
> <message key="plugins.generic.translator.file.confirmCreate">The file "{$filename}" will be created using the English version; you will need to translate all strings in the file. Do you wish to continue?</message>

This is no longer the plugin's behaviour, right? It creates an empty file, but not a file containing English strings (which caused some pain in the past ;-)).

**Comment by asmecher** [comment]
Good spotting -- that locale key isn't even used anymore. Removed throughout.
